name: CMORization request
description: File a CMORization request.
title: "[CMORization request]: "
labels: ["CMORization request"]
projects: ["NorESMhub/CMIP7Cmorization"]
assignees:
  - jgriesfeller
# type: bug (set at the organization level!)
body:
  - type: markdown
    attributes:
      value: "## Mandatory information"
  - type: input
    id: nird_path
    attributes:
      label: Path
      description: Full path to the case(s) of the experiment on NIRD
      placeholder: (e.g. /projects/NS2345K/oyvinds/cases)
    validations:
      required: true
      
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
#   - type: textarea
#     id: optional_information
#     attributes:
#       label: Optional information
#       description: (additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)
#       # placeholder: Tell us what you see!
#       value: "parent_experiment_id

# (e.g. LRTAP-base)
# parent_experiment_rip

# (e.g. r1i1p4f5)
# branch_method

# (e.g. 'Branch-restart from year 2015-01-01 of LRTAP-base',)
# other information
# experiment_rip

# (e.g. r1i1p4f5)
# parent case path

# (e.g. /projects/NS2345K/oyvinds/cases)
# case

# (e.g. NHIST_f19_tn14_Forces_base_20231006)

# ####Physics information:
# Alternative / updated model version based on CMIP6 but updated with parameterisations from projects NFR-KeyClim and H2020-Forces
# Information on aerosol emissions and GHG concentrations, should be added to metdata"
  #   validations:
  #     required: false
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
  # - type: upload
  #   id: screenshots
  #   attributes:
  #     label: Upload screenshots
  #     description: If applicable, add screenshots to help explain your problem.
  #   validations:
  #     required: false
