name: CMORization request with fields
description: CMORization request using partially mandatory fields 
title: "[CMORization request]: "
labels: ["CMORization request"]
projects: ["NorESMhub/CMIP7Cmorization"]
# assignees:
#   - jgriesfeller
# type: bug (set at the organization level!)
body:
  - type: markdown
    attributes:
      value: "## Mandatory information"
  - type: input
    id: nird_path
    attributes:
      label: Full path to the case(s) of the experiment on NIRD
      description: (e.g. /projects/NS2345K/oyvinds/cases)
      # placeholder: 
    validations:
      required: true
      
  - type: input
    id: experiment_id
    attributes:
      label: experiment_id
      description: (e.g. LRTAP-low)
      # placeholder: (e.g. LRTAP-low)
    validations:
      required: true
      
  - type: input
    id: mopdel_id
    attributes:
      label: model_id
      description: (e.g. NorESM2-LM)
      # placeholder: (e.g. NorESM2-LM)
    validations:
      required: true
      
  - type: input
    id: casename_years
    attributes:
      label: CASENAME(s) and years to be CMORized
      # description: CASENAME(s) and years to be CMORized
      description: (e.g. NSSP245_LRTAP-lowdiet_f19_tn14_Forces_20231031, 2015-2050)
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Optional information"
  - type: markdown
    attributes:
      value: | 
        additional information, if the experiment is branched/hybrid restart from previous parent experiment; 
        you may find more information relevant to the experiment_id here:
        https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json
      
  - type: input
    id: parent_experiment_id
    attributes:
      label: parent_experiment_id
      description: (e.g. LRTAP-base)
    validations:
      required: false
      
  - type: input
    id: parent_experiment_rip
    attributes:
      label: parent_experiment_rip
      description: (e.g. r1i1p4f5)
    validations:
      required: false
      
  - type: input
    id: branch_method
    attributes:
      label: branch_method
      description: (e.g. 'Branch-restart from year 2015-01-01 of LRTAP-base',)
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: "### other information"    
      
  - type: input
    id: experiment_rip
    attributes:
      label: experiment_rip
      description: (e.g. r1i1p4f5)
    validations:
      required: false
      
  - type: input
    id: parent_case_path
    attributes:
      label: parent case path
      description: (e.g. /projects/NS2345K/oyvinds/cases)
    validations:
      required: false
      
  - type: input
    id: case
    attributes:
      label: case
      description: (e.g. NHIST_f19_tn14_Forces_base_20231006)
    validations:
      required: false
      
  - type: textarea
    id: pysics_info
    attributes:
      label: Physics information
      description: e.g. Alternative / updated model version based on CMIP6 but updated with parameterisations from projects NFR-KeyClim and H2020-Forces
      render: shell
      
  - type: markdown
    attributes:
      value: "### Progress"
  - type: checkboxes
    id: cmor_status
    attributes:
      label: CMORization status
      description: To be filled by the CMORization team; create sub issues by clicking on the three dots to the right if needed
      options:
        - label: CMORization of atmosphere / land done
        - label: CMORization of ocean / ice done
        - label: published to ESGF

